local lush = require("lush")
local p = require("perfect-blue.palette")

---@diagnostic disable: undefined-global
return lush(function(injected)
  local sym = injected.sym
  return {
    Normal { fg = p.light, bg = "NONE" },
    NormalNC { Normal },
    NormalFloat { fg = p.light, bg = "NONE" },
    FloatBorder { fg = p.slate, bg = "NONE" },
    FloatTitle { fg = p.light, bg = "NONE", gui = "bold" },
    Cursor { fg = p.ink, bg = p.light },
    lCursor { Cursor },
    CursorIM { Cursor },
    TermCursor { Cursor },
    -- Subtle blue-gray selection shared by the editor and file tree.
    CursorLine { bg = "#25303b" },
    NeoTreeCursorLine { CursorLine, gui = "bold" },
    CursorColumn { CursorLine },
    ColorColumn { bg = "NONE" },
    LineNr { fg = p.border },
    CursorLineNr { fg = p.light, gui = "bold" },
    LineNrAbove { LineNr },
    LineNrBelow { LineNr },
    SignColumn { fg = p.slate, bg = "NONE" },
    FoldColumn { SignColumn },
    CursorLineSign { SignColumn },
    CursorLineFold { SignColumn },
    Folded { fg = p.indigo, bg = "NONE" },
    NonText { fg = p.border },
    Whitespace { NonText },
    SpecialKey { NonText },
    EndOfBuffer { fg = p.border },
    -- Match Yuki: neutral, near-black edges without setting the background.
    WinSeparator { fg = "#1a1a1a", bg = "NONE" },
    VertSplit { WinSeparator },
    NeoTreeWinSeparator { WinSeparator },
    NeoTreeVertSplit { WinSeparator },
    Visual { bg = p.selection },
    VisualNOS { Visual },
    Search { fg = p.light, bg = p.selection },
    IncSearch { fg = p.ink, bg = p.indigo, gui = "bold" },
    CurSearch { IncSearch },
    Substitute { IncSearch },
    MatchParen { fg = p.light, bg = p.border, gui = "bold" },
    Pmenu { fg = p.indigo, bg = "NONE" },
    PmenuSel { fg = p.light, bg = p.selection, gui = "bold" },
    PmenuSbar { bg = p.deep },
    PmenuThumb { bg = p.slate },
    PmenuKind { Pmenu },
    PmenuExtra { Pmenu },
    PmenuKindSel { PmenuSel },
    PmenuExtraSel { PmenuSel },
    WildMenu { PmenuSel },
    StatusLine { fg = p.indigo, bg = "#1a1a1a" },
    StatusLineNC { fg = p.slate, bg = "#1a1a1a" },
    TabLine { fg = p.slate, bg = "NONE" },
    WinBarNC { TabLine },
    TabLineFill { TabLine },
    TabLineSel { fg = p.light, bg = "NONE", gui = "bold" },
    WinBar { fg = p.light, bg = "NONE" },
    Directory { fg = p.blue },
    Title { fg = p.light, gui = "bold" },
    ModeMsg { Title },
    MoreMsg { Title },
    Question { Title },
    MsgArea { Normal },
    MsgSeparator { WinSeparator },
    QuickFixLine { PmenuSel },
    Conceal { fg = p.slate },
    Comment { fg = p.slate, gui = "italic" },
    Constant { fg = p.rose },
    String { fg = p.sage },
    Character { String },
    Number { Constant },
    Boolean { Constant },
    Float { Constant },
    Identifier { fg = p.light },
    Function { fg = p.blue, gui = "bold" },
    Keyword { fg = p.indigo, gui = "bold" },
    Statement { Keyword },
    Conditional { Keyword },
    Repeat { Keyword },
    Label { Keyword },
    Exception { Keyword },
    StorageClass { Keyword },
    Operator { fg = p.slate },
    PreProc { fg = p.indigo },
    Include { PreProc },
    Define { PreProc },
    Macro { PreProc },
    PreCondit { PreProc },
    Type { fg = p.light },
    Structure { Type },
    Typedef { Type },
    Special { fg = p.blue },
    SpecialChar { Special },
    Tag { Special },
    Debug { Special },
    SpecialComment { Comment },
    Delimiter { fg = p.slate },
    Underlined { fg = p.light, gui = "underline" },
    Ignore { fg = p.border },
    Error { fg = p.rose, gui = "bold" },
    Todo { fg = p.light, bg = "NONE", gui = "bold" },
    ErrorMsg { Error },
    WarningMsg { fg = p.indigo, gui = "bold" },
    DiagnosticError { fg = p.rose, gui = "bold" },
    DiagnosticSignError { DiagnosticError },
    DiagnosticFloatingError { DiagnosticError },
    DiagnosticVirtualTextError { DiagnosticError },
    DiagnosticVirtualLinesError { DiagnosticError },
    DiagnosticUnderlineError { sp = p.rose, gui = "undercurl" },
    DiagnosticWarn { fg = p.indigo, gui = "bold" },
    DiagnosticSignWarn { DiagnosticWarn },
    DiagnosticFloatingWarn { DiagnosticWarn },
    DiagnosticVirtualTextWarn { DiagnosticWarn },
    DiagnosticVirtualLinesWarn { DiagnosticWarn },
    DiagnosticUnderlineWarn { sp = p.indigo, gui = "undercurl" },
    DiagnosticInfo { fg = p.blue },
    DiagnosticSignInfo { DiagnosticInfo },
    DiagnosticFloatingInfo { DiagnosticInfo },
    DiagnosticVirtualTextInfo { DiagnosticInfo },
    DiagnosticVirtualLinesInfo { DiagnosticInfo },
    DiagnosticUnderlineInfo { sp = p.blue, gui = "undercurl" },
    DiagnosticHint { fg = p.slate, gui = "italic" },
    DiagnosticSignHint { DiagnosticHint },
    DiagnosticFloatingHint { DiagnosticHint },
    DiagnosticVirtualTextHint { DiagnosticHint },
    DiagnosticVirtualLinesHint { DiagnosticHint },
    DiagnosticUnderlineHint { sp = p.slate, gui = "undercurl" },
    DiagnosticOk { fg = p.sage },
    DiagnosticSignOk { DiagnosticOk },
    DiagnosticFloatingOk { DiagnosticOk },
    DiagnosticVirtualTextOk { DiagnosticOk },
    DiagnosticVirtualLinesOk { DiagnosticOk },
    DiagnosticUnderlineOk { sp = p.sage, gui = "undercurl" },
    DiagnosticUnnecessary { fg = p.slate, gui = "italic" },
    DiagnosticDeprecated { gui = "strikethrough" },
    SpellBad { sp = p.rose, gui = "undercurl" },
    SpellCap { sp = p.indigo, gui = "undercurl" },
    SpellLocal { sp = p.indigo, gui = "undercurl" },
    SpellRare { sp = p.indigo, gui = "undercurl" },
    DiffAdd { fg = p.sage, bg = p.deep },
    DiffChange { fg = p.indigo, bg = p.night },
    DiffDelete { fg = p.rose, bg = p.night, gui = "strikethrough" },
    DiffText { fg = p.light, bg = p.selection, gui = "bold" },
    Added { DiffAdd },
    Changed { DiffChange },
    Removed { DiffDelete },
    LspReferenceText { Visual },
    LspReferenceRead { Visual },
    LspReferenceWrite { Visual },
    LspReferenceTarget { Visual },
    LspSignatureActiveParameter { MatchParen },
    LspInlayHint { Comment },
    SnippetTabstop { Visual },
    sym("@variable") { Identifier },
    sym("@variable.parameter") { Identifier },
    sym("@variable.member") { Identifier },
    sym("@property") { Identifier },
    sym("@variable.builtin") { Special },
    sym("@constant.builtin") { Special },
    sym("@string.escape") { Special },
    sym("@string.special") { Special },
    sym("@tag.attribute") { Special },
    sym("@punctuation.special") { Special },
    sym("@constant") { Constant },
    sym("@number") { Constant },
    sym("@number.float") { Constant },
    sym("@boolean") { Constant },
    sym("@string") { String },
    sym("@string.regexp") { String },
    sym("@character") { String },
    sym("@markup.raw") { String },
    sym("@function") { Function },
    sym("@function.builtin") { Function },
    sym("@function.call") { Function },
    sym("@function.method") { Function },
    sym("@function.method.call") { Function },
    sym("@constructor") { Function },
    sym("@keyword") { Keyword },
    sym("@keyword.function") { Keyword },
    sym("@keyword.operator") { Keyword },
    sym("@keyword.return") { Keyword },
    sym("@keyword.import") { Keyword },
    sym("@keyword.repeat") { Keyword },
    sym("@keyword.conditional") { Keyword },
    sym("@keyword.exception") { Keyword },
    sym("@type") { Type },
    sym("@type.builtin") { Type },
    sym("@type.definition") { Type },
    sym("@module") { Type },
    sym("@operator") { Operator },
    sym("@punctuation.delimiter") { Operator },
    sym("@punctuation.bracket") { Delimiter },
    sym("@comment") { Comment },
    sym("@comment.documentation") { Comment },
    sym("@comment.todo") { Todo },
    sym("@comment.note") { Todo },
    sym("@comment.error") { Error },
    sym("@comment.warning") { WarningMsg },
    sym("@markup.heading") { Title },
    sym("@markup.link") { Underlined },
    sym("@markup.link.url") { Underlined },
    sym("@markup") { Normal },
    sym("@linklabel") { Normal },
    sym("@tag") { Tag },
    sym("@markup.strong") { fg = p.light, gui = "bold" },
    sym("@markup.italic") { fg = p.indigo, gui = "italic" },
    sym("@markup.strikethrough") { gui = "strikethrough" },
    sym("@lsp.type.namespace") { Type },
    sym("@lsp.type.type") { Type },
    sym("@lsp.type.class") { Type },
    sym("@lsp.type.enum") { Type },
    sym("@lsp.type.interface") { Type },
    sym("@lsp.type.struct") { Type },
    sym("@lsp.type.typeParameter") { Type },
    sym("@lsp.type.parameter") { Identifier },
    sym("@lsp.type.variable") { Identifier },
    sym("@lsp.type.property") { Identifier },
    sym("@lsp.type.enumMember") { Constant },
    sym("@lsp.type.function") { Function },
    sym("@lsp.type.method") { Function },
    sym("@lsp.type.macro") { PreProc },
    sym("@lsp.type.keyword") { Keyword },
    sym("@lsp.type.comment") { Comment },
    sym("@lsp.type.string") { String },
    sym("@lsp.type.number") { Number },
    sym("@lsp.type.regexp") { String },
    sym("@lsp.type.operator") { Operator },
    sym("@lsp.type.decorator") { Special },
    GitSignsAdd { String },
    NeoTreeGitAdded { String },
    NeoTreeGitUntracked { String },
    GitSignsChange { fg = p.indigo },
    NeoTreeGitModified { fg = p.indigo },
    GitSignsDelete { fg = p.rose },
    NeoTreeGitDeleted { fg = p.rose },
    NeoTreeNormal { Normal },
    NeoTreeNormalNC { Normal },
    NeoTreeDirectoryName { Directory },
    NeoTreeDirectoryIcon { Directory },
    NeoTreeRootName { Directory },
    NeoTreeGitIgnored { Comment },
    NeoTreeGitStaged { String },
    NeoTreeGitConflict { Error },
    TelescopeNormal { NormalFloat },
    TelescopePromptNormal { NormalFloat },
    TelescopeResultsNormal { NormalFloat },
    TelescopePreviewNormal { NormalFloat },
    TelescopeBorder { FloatBorder },
    TelescopePromptBorder { FloatBorder },
    TelescopeResultsBorder { FloatBorder },
    TelescopePreviewBorder { FloatBorder },
    TelescopeSelection { PmenuSel },
    TelescopeMatching { Function },
    TelescopeTitle { FloatTitle },
    TelescopePromptTitle { FloatTitle },
    TelescopeResultsTitle { FloatTitle },
    TelescopePreviewTitle { FloatTitle },
    CmpItemAbbr { Normal },
    BlinkCmpLabel { Normal },
    CmpItemAbbrMatch { Function },
    CmpItemAbbrMatchFuzzy { Function },
    BlinkCmpLabelMatch { Function },
    CmpItemAbbrDeprecated { DiagnosticDeprecated },
    CmpItemMenu { Comment },
    BlinkCmpLabelDescription { Comment },
    BlinkCmpMenu { Pmenu },
    BlinkCmpMenuBorder { FloatBorder },
    BlinkCmpMenuSelection { PmenuSel },
    SnacksNormal { NormalFloat },
    SnacksPickerNormal { NormalFloat },
    SnacksPickerBorder { FloatBorder },
    SnacksPickerMatch { Function },
    SnacksPickerDir { Comment },
    SnacksPickerSelected { PmenuSel },
    SnacksDashboardHeader { Title },
    SnacksDashboardTitle { Title },
    SnacksDashboardKey { Title },
    LazyNormal { NormalFloat },
    MasonNormal { NormalFloat },
    LazyButton { Pmenu },
    MasonHighlightBlock { Pmenu },
    LazyButtonActive { PmenuSel },
    MasonHighlightBlockBold { PmenuSel },
    NoiceCmdlinePopup { NormalFloat },
    NoicePopup { NormalFloat },
    NoiceCmdlinePopupBorder { FloatBorder },
    NoicePopupBorder { FloatBorder },
  }
end)
