-- Generated from lua/lush_theme/perfect-blue.lua by Shipwright.
local colors = {
-- PATCH_OPEN
Normal = {fg = "#b0bacb", bg = "NONE"},
BlinkCmpLabel = {link = "Normal"},
CmpItemAbbr = {link = "Normal"},
MsgArea = {link = "Normal"},
NeoTreeNormal = {link = "Normal"},
NeoTreeNormalNC = {link = "Normal"},
NormalNC = {link = "Normal"},
["@linklabel"] = {link = "Normal"},
["@markup"] = {link = "Normal"},
ColorColumn = {bg = "NONE"},
Comment = {fg = "#63798b", italic = true},
BlinkCmpLabelDescription = {link = "Comment"},
CmpItemMenu = {link = "Comment"},
LspInlayHint = {link = "Comment"},
NeoTreeGitIgnored = {link = "Comment"},
SnacksPickerDir = {link = "Comment"},
SpecialComment = {link = "Comment"},
["@comment"] = {link = "Comment"},
["@comment.documentation"] = {link = "Comment"},
["@lsp.type.comment"] = {link = "Comment"},
Conceal = {fg = "#63798b"},
Constant = {fg = "#a37e8f"},
Boolean = {link = "Constant"},
Float = {link = "Constant"},
Number = {link = "Constant"},
["@boolean"] = {link = "Constant"},
["@constant"] = {link = "Constant"},
["@lsp.type.enumMember"] = {link = "Constant"},
["@number"] = {link = "Constant"},
["@number.float"] = {link = "Constant"},
Cursor = {fg = "#000000", bg = "#b0bacb"},
CursorIM = {link = "Cursor"},
TermCursor = {link = "Cursor"},
lCursor = {link = "Cursor"},
CursorLine = {bg = "#25303b"},
CursorColumn = {link = "CursorLine"},
CursorLineNr = {fg = "#b0bacb", bold = true},
Delimiter = {fg = "#63798b"},
["@punctuation.bracket"] = {link = "Delimiter"},
DiagnosticDeprecated = {strikethrough = true},
CmpItemAbbrDeprecated = {link = "DiagnosticDeprecated"},
DiagnosticError = {fg = "#a37e8f", bold = true},
DiagnosticFloatingError = {link = "DiagnosticError"},
DiagnosticSignError = {link = "DiagnosticError"},
DiagnosticVirtualLinesError = {link = "DiagnosticError"},
DiagnosticVirtualTextError = {link = "DiagnosticError"},
DiagnosticHint = {fg = "#63798b", italic = true},
DiagnosticFloatingHint = {link = "DiagnosticHint"},
DiagnosticSignHint = {link = "DiagnosticHint"},
DiagnosticVirtualLinesHint = {link = "DiagnosticHint"},
DiagnosticVirtualTextHint = {link = "DiagnosticHint"},
DiagnosticInfo = {fg = "#4993ba"},
DiagnosticFloatingInfo = {link = "DiagnosticInfo"},
DiagnosticSignInfo = {link = "DiagnosticInfo"},
DiagnosticVirtualLinesInfo = {link = "DiagnosticInfo"},
DiagnosticVirtualTextInfo = {link = "DiagnosticInfo"},
DiagnosticOk = {fg = "#6b8581"},
DiagnosticFloatingOk = {link = "DiagnosticOk"},
DiagnosticSignOk = {link = "DiagnosticOk"},
DiagnosticVirtualLinesOk = {link = "DiagnosticOk"},
DiagnosticVirtualTextOk = {link = "DiagnosticOk"},
DiagnosticUnderlineError = {sp = "#a37e8f", undercurl = true},
DiagnosticUnderlineHint = {sp = "#63798b", undercurl = true},
DiagnosticUnderlineInfo = {sp = "#4993ba", undercurl = true},
DiagnosticUnderlineOk = {sp = "#6b8581", undercurl = true},
DiagnosticUnderlineWarn = {sp = "#7191af", undercurl = true},
DiagnosticUnnecessary = {fg = "#63798b", italic = true},
DiagnosticWarn = {fg = "#7191af", bold = true},
DiagnosticFloatingWarn = {link = "DiagnosticWarn"},
DiagnosticSignWarn = {link = "DiagnosticWarn"},
DiagnosticVirtualLinesWarn = {link = "DiagnosticWarn"},
DiagnosticVirtualTextWarn = {link = "DiagnosticWarn"},
DiffAdd = {fg = "#6b8581", bg = "#0f1525"},
Added = {link = "DiffAdd"},
DiffChange = {fg = "#7191af", bg = "#080b16"},
Changed = {link = "DiffChange"},
DiffDelete = {fg = "#a37e8f", bg = "#080b16", strikethrough = true},
Removed = {link = "DiffDelete"},
DiffText = {fg = "#b0bacb", bg = "#253d52", bold = true},
Directory = {fg = "#4993ba"},
NeoTreeDirectoryIcon = {link = "Directory"},
NeoTreeDirectoryName = {link = "Directory"},
NeoTreeRootName = {link = "Directory"},
EndOfBuffer = {fg = "#3e566c"},
Error = {fg = "#a37e8f", bold = true},
ErrorMsg = {link = "Error"},
NeoTreeGitConflict = {link = "Error"},
["@comment.error"] = {link = "Error"},
FloatBorder = {fg = "#63798b", bg = "NONE"},
BlinkCmpMenuBorder = {link = "FloatBorder"},
NoiceCmdlinePopupBorder = {link = "FloatBorder"},
NoicePopupBorder = {link = "FloatBorder"},
SnacksPickerBorder = {link = "FloatBorder"},
TelescopeBorder = {link = "FloatBorder"},
TelescopePreviewBorder = {link = "FloatBorder"},
TelescopePromptBorder = {link = "FloatBorder"},
TelescopeResultsBorder = {link = "FloatBorder"},
FloatTitle = {fg = "#b0bacb", bg = "NONE", bold = true},
TelescopePreviewTitle = {link = "FloatTitle"},
TelescopePromptTitle = {link = "FloatTitle"},
TelescopeResultsTitle = {link = "FloatTitle"},
TelescopeTitle = {link = "FloatTitle"},
Folded = {fg = "#7191af", bg = "NONE"},
Function = {fg = "#4993ba", bold = true},
BlinkCmpLabelMatch = {link = "Function"},
CmpItemAbbrMatch = {link = "Function"},
CmpItemAbbrMatchFuzzy = {link = "Function"},
SnacksPickerMatch = {link = "Function"},
TelescopeMatching = {link = "Function"},
["@constructor"] = {link = "Function"},
["@function"] = {link = "Function"},
["@function.builtin"] = {link = "Function"},
["@function.call"] = {link = "Function"},
["@function.method"] = {link = "Function"},
["@function.method.call"] = {link = "Function"},
["@lsp.type.function"] = {link = "Function"},
["@lsp.type.method"] = {link = "Function"},
GitSignsChange = {fg = "#7191af"},
GitSignsDelete = {fg = "#a37e8f"},
Identifier = {fg = "#b0bacb"},
["@lsp.type.parameter"] = {link = "Identifier"},
["@lsp.type.property"] = {link = "Identifier"},
["@lsp.type.variable"] = {link = "Identifier"},
["@property"] = {link = "Identifier"},
["@variable"] = {link = "Identifier"},
["@variable.member"] = {link = "Identifier"},
["@variable.parameter"] = {link = "Identifier"},
Ignore = {fg = "#3e566c"},
IncSearch = {fg = "#000000", bg = "#7191af", bold = true},
CurSearch = {link = "IncSearch"},
Substitute = {link = "IncSearch"},
Keyword = {fg = "#7191af", bold = true},
Conditional = {link = "Keyword"},
Exception = {link = "Keyword"},
Label = {link = "Keyword"},
Repeat = {link = "Keyword"},
Statement = {link = "Keyword"},
StorageClass = {link = "Keyword"},
["@keyword"] = {link = "Keyword"},
["@keyword.conditional"] = {link = "Keyword"},
["@keyword.exception"] = {link = "Keyword"},
["@keyword.function"] = {link = "Keyword"},
["@keyword.import"] = {link = "Keyword"},
["@keyword.operator"] = {link = "Keyword"},
["@keyword.repeat"] = {link = "Keyword"},
["@keyword.return"] = {link = "Keyword"},
["@lsp.type.keyword"] = {link = "Keyword"},
LineNr = {fg = "#3e566c"},
LineNrAbove = {link = "LineNr"},
LineNrBelow = {link = "LineNr"},
MatchParen = {fg = "#b0bacb", bg = "#3e566c", bold = true},
LspSignatureActiveParameter = {link = "MatchParen"},
NeoTreeCursorLine = {bg = "#25303b", bold = true},
NeoTreeGitDeleted = {fg = "#a37e8f"},
NeoTreeGitModified = {fg = "#7191af"},
NonText = {fg = "#3e566c"},
SpecialKey = {link = "NonText"},
Whitespace = {link = "NonText"},
NormalFloat = {fg = "#b0bacb", bg = "NONE"},
LazyNormal = {link = "NormalFloat"},
MasonNormal = {link = "NormalFloat"},
NoiceCmdlinePopup = {link = "NormalFloat"},
NoicePopup = {link = "NormalFloat"},
SnacksNormal = {link = "NormalFloat"},
SnacksPickerNormal = {link = "NormalFloat"},
TelescopeNormal = {link = "NormalFloat"},
TelescopePreviewNormal = {link = "NormalFloat"},
TelescopePromptNormal = {link = "NormalFloat"},
TelescopeResultsNormal = {link = "NormalFloat"},
["@lsp.type.number"] = {link = "Number"},
Operator = {fg = "#63798b"},
["@lsp.type.operator"] = {link = "Operator"},
["@operator"] = {link = "Operator"},
["@punctuation.delimiter"] = {link = "Operator"},
Pmenu = {fg = "#7191af", bg = "NONE"},
BlinkCmpMenu = {link = "Pmenu"},
LazyButton = {link = "Pmenu"},
MasonHighlightBlock = {link = "Pmenu"},
PmenuExtra = {link = "Pmenu"},
PmenuKind = {link = "Pmenu"},
PmenuSbar = {bg = "#0f1525"},
PmenuSel = {fg = "#b0bacb", bg = "#253d52", bold = true},
BlinkCmpMenuSelection = {link = "PmenuSel"},
LazyButtonActive = {link = "PmenuSel"},
MasonHighlightBlockBold = {link = "PmenuSel"},
PmenuExtraSel = {link = "PmenuSel"},
PmenuKindSel = {link = "PmenuSel"},
QuickFixLine = {link = "PmenuSel"},
SnacksPickerSelected = {link = "PmenuSel"},
TelescopeSelection = {link = "PmenuSel"},
WildMenu = {link = "PmenuSel"},
PmenuThumb = {bg = "#63798b"},
PreProc = {fg = "#7191af"},
Define = {link = "PreProc"},
Include = {link = "PreProc"},
Macro = {link = "PreProc"},
PreCondit = {link = "PreProc"},
["@lsp.type.macro"] = {link = "PreProc"},
Search = {fg = "#b0bacb", bg = "#253d52"},
SignColumn = {fg = "#63798b", bg = "NONE"},
CursorLineFold = {link = "SignColumn"},
CursorLineSign = {link = "SignColumn"},
FoldColumn = {link = "SignColumn"},
Special = {fg = "#4993ba"},
Debug = {link = "Special"},
SpecialChar = {link = "Special"},
Tag = {link = "Special"},
["@constant.builtin"] = {link = "Special"},
["@lsp.type.decorator"] = {link = "Special"},
["@punctuation.special"] = {link = "Special"},
["@string.escape"] = {link = "Special"},
["@string.special"] = {link = "Special"},
["@tag.attribute"] = {link = "Special"},
["@variable.builtin"] = {link = "Special"},
SpellBad = {sp = "#a37e8f", undercurl = true},
SpellCap = {sp = "#7191af", undercurl = true},
SpellLocal = {sp = "#7191af", undercurl = true},
SpellRare = {sp = "#7191af", undercurl = true},
StatusLine = {fg = "#7191af", bg = "#1a1a1a"},
StatusLineNC = {fg = "#63798b", bg = "#1a1a1a"},
String = {fg = "#6b8581"},
Character = {link = "String"},
GitSignsAdd = {link = "String"},
NeoTreeGitAdded = {link = "String"},
NeoTreeGitStaged = {link = "String"},
NeoTreeGitUntracked = {link = "String"},
["@character"] = {link = "String"},
["@lsp.type.regexp"] = {link = "String"},
["@lsp.type.string"] = {link = "String"},
["@markup.raw"] = {link = "String"},
["@string"] = {link = "String"},
["@string.regexp"] = {link = "String"},
TabLine = {fg = "#63798b", bg = "NONE"},
TabLineFill = {link = "TabLine"},
WinBarNC = {link = "TabLine"},
TabLineSel = {fg = "#b0bacb", bg = "NONE", bold = true},
["@tag"] = {link = "Tag"},
Title = {fg = "#b0bacb", bold = true},
ModeMsg = {link = "Title"},
MoreMsg = {link = "Title"},
Question = {link = "Title"},
SnacksDashboardHeader = {link = "Title"},
SnacksDashboardKey = {link = "Title"},
SnacksDashboardTitle = {link = "Title"},
["@markup.heading"] = {link = "Title"},
Todo = {fg = "#b0bacb", bg = "NONE", bold = true},
["@comment.note"] = {link = "Todo"},
["@comment.todo"] = {link = "Todo"},
Type = {fg = "#b0bacb"},
Structure = {link = "Type"},
Typedef = {link = "Type"},
["@lsp.type.class"] = {link = "Type"},
["@lsp.type.enum"] = {link = "Type"},
["@lsp.type.interface"] = {link = "Type"},
["@lsp.type.namespace"] = {link = "Type"},
["@lsp.type.struct"] = {link = "Type"},
["@lsp.type.type"] = {link = "Type"},
["@lsp.type.typeParameter"] = {link = "Type"},
["@module"] = {link = "Type"},
["@type"] = {link = "Type"},
["@type.builtin"] = {link = "Type"},
["@type.definition"] = {link = "Type"},
Underlined = {fg = "#b0bacb", underline = true},
["@markup.link"] = {link = "Underlined"},
["@markup.link.url"] = {link = "Underlined"},
Visual = {bg = "#253d52"},
LspReferenceRead = {link = "Visual"},
LspReferenceTarget = {link = "Visual"},
LspReferenceText = {link = "Visual"},
LspReferenceWrite = {link = "Visual"},
SnippetTabstop = {link = "Visual"},
VisualNOS = {link = "Visual"},
WarningMsg = {fg = "#7191af", bold = true},
["@comment.warning"] = {link = "WarningMsg"},
WinBar = {fg = "#b0bacb", bg = "NONE"},
WinSeparator = {fg = "#1a1a1a", bg = "NONE"},
MsgSeparator = {link = "WinSeparator"},
NeoTreeVertSplit = {link = "WinSeparator"},
NeoTreeWinSeparator = {link = "WinSeparator"},
VertSplit = {link = "WinSeparator"},
["@markup.italic"] = {fg = "#7191af", italic = true},
["@markup.strikethrough"] = {strikethrough = true},
["@markup.strong"] = {fg = "#b0bacb", bold = true},
-- PATCH_CLOSE
}

vim.cmd("highlight clear")
vim.g.colors_name = "perfect-blue"
for group, attrs in pairs(colors) do
  vim.api.nvim_set_hl(0, group, attrs)
end
package.loaded["perfect-blue.palette"] = nil
package.loaded["perfect-blue.terminal"] = nil
require("perfect-blue.terminal")()
